---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - docker.io
    - docker-compose
    - git

- name: Add user to docker group
  user:
    name: amor
    groups: docker
    append: yes

- name: Copy project files to target VM
  copy:
    src: "{{ playbook_dir }}/../"
    dest: /opt/nginx-ansible-docker/
    owner: root
    group: root
    mode: "0755"
    remote_src: no
